Zaggoware.BugTracker.Web/Models/Notification.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Zaggoware.BugTracker.Web.Models
{
    public class Notification
    {
        public const string IndexKey = "Notifications";

        public NotifyType Type { get; set; }

        public string Message { get; set; }

        public Notification()
        {
        }

        public Notification(NotifyType type, string message)
            : this()
        {
            this.Type = type;
            this.Message = message;
        }
    }
}

Zaggoware.BugTracker.Web/Controllers/OrganizationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Zaggoware.BugTracker.Web.Controllers
{
    using Zaggoware.BugTracker.Common.Tagging;
    using Zaggoware.BugTracker.Services;
	using Zaggoware.BugTracker.Web.Models;

    public class OrganizationsController : BaseController
    {
	    private readonly IOrganizationService organizationService;

	    public OrganizationsController(IUserService userService, IOrganizationService organizationService)
			: base(userService)
		{
		    this.organizationService = organizationService;
		}

	    [HttpGet]
        public ActionResult Index()
        {
            var organizations = this.organizationService.GetOrganizations();

            return this.View(organizations);
        }

        [HttpGet]
	    public ActionResult Create()
        {
            return
                this.View(
                    new OrganizationModel
                        {
                            Managers =
                                new TagList
                                    {
                                        new TagListItem { HiddenValue = 1, Label = "Patrick" },
                                        new TagListItem { HiddenValue = 3, Label = "Joeri" }
                                    }
                        });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
	    public ActionResult Create(OrganizationModel model)
        {
            if (ModelState.IsValid)
            {
                var organization = this.organizationService.CreateOrganization(model.Name, true);

                return this.RedirectToAction("Index");
            }

            return this.View(model);
        }
    }
}

Zaggoware.BugTracker.Web/Views/Shared/_Layout.cshtml
@using Zaggoware.BugTracker.Web.Helpers
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - @Titles.ApplicationName</title>
    @Styles.Render("~/content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("_Navigation")

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - @Titles.ApplicationName</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    
    @if (HtmlExtensions.IncludeTagger)
    {
        <script type="text/javascript" src="@Url.Content("~/scripts/Tagger.js")"></script>
        <script type="text/javascript">
            $(function () {
                console.log(Zaggoware.Tagging.Tagger);
                Zaggoware.Tagging.Tagger.initialize();
            });
        </script>
    }

    @RenderSection("scripts", required: false)
</body>
</html>

Zaggoware.BugTracker.Web/Views/Shared/_Navigation.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink(Titles.ApplicationName, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                @if (Request.IsAuthenticated || ViewBag.CurrentUser != null)
                {
                    <li>@Html.ActionLink(Titles.Dashboard, "Index", "Home")</li>
                    <li>@Html.ActionLink(Titles.Projects, "Index", "Organizations")</li>
                }
                else
                {
                    <li>@Html.ActionLink(Titles.Login, "Index", "Home")</li>
                    <li>@Html.ActionLink(Titles.About, "About", "Home")</li>
                }
            </ul>
        </div>
    </div>
</div>

Zaggoware.BugTracker.Web/Views/Shared/_Notifications.cshtml
@{
    var notifications = TempData[Notification.IndexKey] as IEnumerable<Notification>;
}

@if (notifications != null)
{
    foreach (var notification in notifications)
    {
        string alertType;

        switch (notification.Type)
        {
            case NotifyType.Success:
                alertType = "success";
                break;
            case NotifyType.Warning:
                alertType = "warning";
                break;
            case NotifyType.Error:
                alertType = "danger";
                break;
            default:
                alertType = "info";
                break;
        }
        
        <div class="alert alert-dismissable alert-@alertType">
            <p>@notification.Message</p>
        </div>
    }
}